name: grocerease
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_staggered_grid_view: ^0.6.2
  google_maps_flutter: ^2.2.6
  location: ^4.2.0
  url_launcher: ^6.1.11
  auto_size_text: 3.0.0
  google_fonts: 4.0.3
  firebase_core: ^2.14.0
  share_plus: ^7.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  firebase_database: ^10.2.3
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  firebase_storage: ^11.2.3
  http: ^0.13.5
  flutter_stripe: ^9.2.1
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    -
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf